using System;
using System.ComponentModel.DataAnnotations;

namespace Converge.Configuration.DTOs
{
    public enum ConfigurationScope
    {
        Global,
        Tenant,
        Company
    }

    public class CreateConfigRequest
    {
        [Required]
        public string Key { get; set; } = null!;

        [Required]
        public string Value { get; set; } = null!;

        /// <summary>
        /// Scope is extracted from Bearer token, not required in request body
        /// </summary>
        public ConfigurationScope? Scope { get; set; }

        /// <summary>
        /// Domain is optional and extracted from Bearer token if needed
        /// </summary>
        public string? Domain { get; set; }

        /// <summary>
        /// TenantId is extracted from Bearer token, not settable by client
        /// </summary>
        public Guid? TenantId { get; set; }

        // CompanyId is always generated by the service for Company scope; not settable by client

        /// <summary>
        /// Validates the request based on the scope
        /// </summary>
        public void Validate()
        {
            // If Scope is not provided, skip validation (will be set from token)
            if (!Scope.HasValue)
                return;

            switch (Scope.Value)
            {
                case ConfigurationScope.Company:
                case ConfigurationScope.Tenant:
                    if (string.IsNullOrWhiteSpace(Domain))
                        throw new ValidationException("Domain is required for Tenant and Company scopes.");
                    break;

                case ConfigurationScope.Global:
                    if (!string.IsNullOrWhiteSpace(Domain))
                        throw new ValidationException("Domain is not allowed for Global scope.");
                    break;
            }
        }
    }
}
