FROM mcr.microsoft.com/dotnet/aspnet:10 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Converge.Configuration.API/Converge.Configuration.API.csproj"
RUN dotnet publish "Converge.Configuration.API/Converge.Configuration.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Converge.Configuration.API.dll"]